### ISSUE TITLE
Missing phpunit.xml.dist

### ISSUE THREAD

**Issue by ashsmith** [meanbee/example-magento2-module#1]
Running the phpunit command without a phpunit.xml.dist resulted in no tests being found.

Adding a basic phpunit.xml.dist to the root will resolve:

```
<?xml version="1.0"?>
<phpunit bootstrap="./vendor/autoload.php" colors="true">
    <testsuite name="example-magento2-module unit tests">
        <directory suffix="Test.php">src/Test/Unit</directory>
    </testsuite>
</phpunit>
```

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
